### ISSUE TITLE
Add Datatypes How To for App Developers

### ISSUE THREAD

**Issue by bendhouseart** [brainlife/docs#136]
Having trouble figuring out how to create a datatype in concert with the registration of a new brainlife.io app. [The documentation mentions](https://brainlife.io/docs/user/datatypes/) discussing this process with sys admin's, and the[ link to datatypes ](https://github.com/brainlife/datatypes) found on [https://brainlife.io/docs/](https://brainlife.io/docs/) seems to be dead.

Would be happy to make a PR closing this issue, but I'm not sure where to start.

**Comment by anibalsolon** [comment]
Datatypes are not open to be created, given they require to be discussed with the team on how to appropriately create them.
