### ISSUE TITLE
"Permalinks" for dataset queries

### ISSUE THREAD

**Issue by mih** [brainlife/docs#30]
[Apologies for filing this here, I could not find a more appropriate spot]

The dataset search feature is very nice and of great utility. It would be nice to be able to link to a particular query, so it can be shared (e.g. via email). In other words: a link that brings any interested party to a page like this:

![image](https://user-images.githubusercontent.com/136479/73178902-81bbb280-4112-11ea-9113-a25780d6c081.png)

Thanks in advance!

**Comment by soichih** [comment]
@mih Feel free to use this repo to post feature requests > https://github.com/brainlife/warehouse/issues to post feature requests ("warehouse" is the code name for brainlife.io frontend).

I will update so that search query will stick with the URL so you can copy/paste the URL to share the list.

**Comment by mih** [comment]
@soichih Awesome, thanks! Sorry, I forgot the "warehouse" code name.

**Comment by soichih** [comment]
This has been implemented. 
> https://brainlife.io/datasets#%7B%22query%22%3A%22hanke%22%2C%22datatypes%22%3A%5B%5D%7D
