### ISSUE TITLE
Unintentional / potentially confusing use of term "datasets"?

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/docs#85]
In the [datatype tag subsection](https://brainlife.io/docs/user/datatypes/#datatype-tags) there is the following assertion:

> You should only use this tag to specify the information on **datasets**, not generalize it.

(Bold added to highlight potential issue)

To my understanding "datasets" refers to entities like those listed on the [datasets](https://brainlife.io/datasets) page.  In this way, a dataset appears to primarily defined/delineated as a collection of data objects, typically instanced across subjects, and collectively bound by some combination of collection methodologies, subject characteristics, or project-level investigator intents.  

However, the use here is a bit confusing, as it appears to blur the distinction between "datasets" and "datatypes" or "data objects". It seems to me that the appropriate term might be "datatypes", and the subsequent example provided (dwi datatype tags) seems consistent with this.  I'm not 100% certain though, so I didn't want to unilaterally impose changes without inquiring with others about this first.

**Comment by soichih** [comment]
Yes, you are correct about "dataset". We should use "data object" rather than "dataset". I've updated the datatype page > https://brainlife.io/docs/user/datatypes/
